"""fix column position unique index

Revision ID: 057fad68d446
Revises: 62776d211b7c
Create Date: 2026-09-21 08:07:32.618657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057fad68d446'
down_revision: Union[str, None] = '62776d211b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_column_board_position', 'columns', type_='unique')
    op.create_index('uq_column_board_position', 'columns', ['board_id', 'position'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_column_board_position', table_name='columns', postgresql_where='deleted_at IS NULL')
    op.create_unique_constraint('uq_column_board_position', 'columns', ['board_id', 'position'])
    # ### end Alembic commands ###
