"""add task archive to task model

Revision ID: 0b70ecee0802
Revises: 3efde4463e2b
Create Date: 2026-08-12 08:21:35.903415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b70ecee0802'
down_revision: Union[str, None] = '3efde4463e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_tasks_is_archived'), 'tasks', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_is_archived'), table_name='tasks')
    op.drop_column('tasks', 'is_archived')
    # ### end Alembic commands ###
