"""add is_completed to tasks

Revision ID: 3efde4463e2b
Revises: 5e94efd91b8d
Create Date: 2026-08-12 07:53:32.374611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efde4463e2b'
down_revision: Union[str, None] = '5e94efd91b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_tasks_is_completed'), 'tasks', ['is_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_is_completed'), table_name='tasks')
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
