"""add user_id to time logs

Revision ID: 5e07a8895498
Revises: 0b70ecee0802
Create Date: 2026-08-31 04:34:32.017607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e07a8895498'
down_revision: Union[str, None] = '0b70ecee0802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_logs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_time_logs_user_id'), 'time_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'time_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.drop_index(op.f('ix_time_logs_user_id'), table_name='time_logs')
    op.drop_column('time_logs', 'user_id')
    # ### end Alembic commands ###
