"""update_board_member_unique_index

Revision ID: 5e94efd91b8d
Revises: 3eb91cd93dab
Create Date: 2026-07-21 05:57:11.078547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e94efd91b8d'
down_revision: Union[str, None] = '3eb91cd93dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_board_member', 'board_members', type_='unique')
    op.create_index('uq_board_member_active', 'board_members', ['board_id', 'user_id'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_board_member_active', table_name='board_members', postgresql_where='deleted_at IS NULL')
    op.create_unique_constraint('uq_board_member', 'board_members', ['board_id', 'user_id'])
    # ### end Alembic commands ###
