"""create activities table

Revision ID: 62776d211b7c
Revises: 5e07a8895498
Create Date: 2026-09-08 06:32:14.187223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62776d211b7c'
down_revision: Union[str, None] = '5e07a8895498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_board_id'), 'activities', ['board_id'], unique=False)
    op.create_index(op.f('ix_activities_task_id'), 'activities', ['task_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.drop_index('uq_board_member_active', table_name='board_members', postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint('uq_board_member', 'board_members', ['board_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_board_member', 'board_members', type_='unique')
    op.create_index('uq_board_member_active', 'board_members', ['board_id', 'user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_task_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_board_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
