"""add board_member_model

Revision ID: d3ba790aa76d
Revises: 3a7b9c2d1e4f
Create Date: 2026-07-13 04:34:18.337893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ba790aa76d'
down_revision: Union[str, None] = '3a7b9c2d1e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='board_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'user_id', name='uq_board_member')
    )
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_members_deleted_at'), 'board_members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_board_members_user_id'), 'board_members', ['user_id'], unique=False)
    op.drop_index('app_logs_timestamp_idx', table_name='app_logs')
    op.drop_index('idx_app_logs_action', table_name='app_logs', postgresql_where='(action IS NOT NULL)')
    op.drop_index('idx_app_logs_level', table_name='app_logs')
    op.drop_index('idx_app_logs_log_type', table_name='app_logs')
    op.drop_index('idx_app_logs_request', table_name='app_logs', postgresql_where='(request_id IS NOT NULL)')
    op.drop_index('idx_app_logs_user', table_name='app_logs', postgresql_where='(user_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_app_logs_user', 'app_logs', ['user_id', sa.text('timestamp DESC')], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_app_logs_request', 'app_logs', ['request_id', sa.text('timestamp DESC')], unique=False, postgresql_where='(request_id IS NOT NULL)')
    op.create_index('idx_app_logs_log_type', 'app_logs', ['log_type', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_app_logs_level', 'app_logs', ['level', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_app_logs_action', 'app_logs', ['action', sa.text('timestamp DESC')], unique=False, postgresql_where='(action IS NOT NULL)')
    op.create_index('app_logs_timestamp_idx', 'app_logs', [sa.text('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_board_members_user_id'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_deleted_at'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.drop_table('board_members')
    # ### end Alembic commands ###
